### ISSUE TITLE
你好，问一下 Cesium 能添加自定义参数的地图吗

### ISSUE THREAD

**Issue by gee1k** [AJJackGIS/Cesium#1]

**Comment by AJJackGIS** [comment]
可以啊，这个得看你的实际情况了

**Comment by gee1k** [comment]
@AJJackGIS  自定义切图原点、分辨率、等参数

**Comment by AJJackGIS** [comment]
你可以 重写 TileCoordinatesImageryProvider 类的 requestImage(x, y, level, request)方法 ，根据x,y,level参数转换为你自己的自定义规则，用这个类加载就可以了,可以参考官网的Imagery Layers Manipulation 例子
